version: "3"

networks:
  todo:

services:
  mysql:
    image: coney/mysql:5
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    networks:
      todo:
        aliases:
          - mysql
    ports:
      - "3306:3306"
  config-server:
    image: huangyanyan/config-server:${VER}
    networks:
      todo:
        aliases:
          - config-server
    ports:
      - "8099:8099"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  gateway:
    image: huangyanyan/gateway:${VER}
    depends_on:
      - config-server
    networks:
      todo:
        aliases:
          - gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  user-service:
    image: huangyanyan/user-service:${VER}
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
    depends_on:
      - mysql
      - config-server
      - gateway
    networks:
      todo:
        aliases:
          - user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
  todo-service:
    image: huangyanyan/todo-service:${VER}
    deploy:
      replicas: 2
      restart_policy:
        delay: 10s
    depends_on:
      - mysql
      - config-server
      - gateway
    networks:
      todo:
        aliases:
          - todo-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default




